AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''
  ComeInDBHost:
    Type: String
    Description: db host
    Default: 'comeindb2.cstlg3ladsl5.ap-southeast-1.rds.amazonaws.com'
  ComeInDBPort:
    Type: String
    Description: db port
    Default: '5432'
  ComeInDBUsername:
    Type: String
    Description: db username
    Default: 'comein'
  ComeInDBPassword:
    Type: String
    Description: db password
    Default: 'q2deqkTna5GyxxHlkR1d'
  ComeInDBInstance:
    Type: String
    Description: db instance
    Default: 'comein'
  ComeInCognitoUserPoolId:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'ap-southeast-1_sH5GQOfGD'
  ComeInCognitoRegion:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'ap-southeast-1'
  ComeInResponseTemplate:
    Type: String
    Description: request-template
    Default: $input.json('$.json-body')
  ComeInRequestTemplate:
    Type: String
    Description: request-template
    Default: |
      #set($allParams = $input.params())
      {
      "body" : $input.body,
      "json-body" : $input.json('$'),
      "path" : "$context.resourcePath",
      "profile":{
         "email" : "$context.authorizer.claims.email",
         "comein-id":"$context.authorizer.claims['custom:comein_id']",
         "ref-name" : "$context.authorizer.claims.name",
         "sub":"$context.authorizer.claims.sub"
         
        },
      "path-parameters": $allParams.get('path'),
      "query-string-parameters": $allParams.get('querystring'),
      "params" : {
      #foreach($type in $allParams.keySet())
          #set($params = $allParams.get($type))
      "$type" : {
          #foreach($paramName in $params.keySet())
          "$paramName" : "$util.escapeJavaScript($params.get($paramName))"
              #if($foreach.hasNext),#end
          #end
      }
          #if($foreach.hasNext),#end
      #end
      },
      "stage-variables" : {
      #foreach($key in $stageVariables.keySet())
      "$key" : "$util.escapeJavaScript($stageVariables.get($key))"
          #if($foreach.hasNext),#end
      #end
      },
      "context" : {
          "account-id" : "$context.identity.accountId",
          "api-id" : "$context.apiId",
          "api-key" : "$context.identity.apiKey",
          "authorizer-principal-id" : "$context.authorizer.principalId",
          "caller" : "$context.identity.caller",
          "cognito-authentication-provider" : "$context.identity.cognitoAuthenticationProvider",
          "cognito-authentication-type" : "$context.identity.cognitoAuthenticationType",
          "cognito-identity-id" : "$context.identity.cognitoIdentityId",
          "cognito-identity-pool-id" : "$context.identity.cognitoIdentityPoolId",
          "http-method" : "$context.httpMethod",
          "stage" : "$context.stage",
          "source-ip" : "$context.identity.sourceIp",
          "user" : "$context.identity.user",
          "user-agent" : "$context.identity.userAgent",
          "user-arn" : "$context.identity.userArn",
          "request-id" : "$context.requestId",
          "resource-id" : "$context.resourceId",
          "resource-path" : "$context.resourcePath"
          }
      }
    
    
    

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:

  ComeInRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      # Body:
        # OpenAPI specification: null
      Description: ComeIn API
      Name: MyComeInAPI
      
  ComeInAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:  
      Name: comein_authorizer
      Type: COGNITO_USER_POOLS
      RestApiId: !Ref ComeInRestApi
      IdentitySource: method.request.header.comein_auth
      ProviderARNs: 
        - !Sub arn:aws:cognito-idp:${ComeInCognitoRegion}:${AWS::AccountId}:userpool/${ComeInCognitoUserPoolId}
      
  GetHelloWorldFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-GetHelloWorldFunc'
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Environment:
        Variables:
          spring_cloud_function_definition: getHelloWorld
          DB_HOST: !Ref ComeInDBHost
          DB_PORT: !Ref ComeInDBPort
          DB_INSTANCE: !Ref ComeInDBInstance
          DB_USERNAME: !Ref ComeInDBUsername
          DB_PASSWORD: !Ref ComeInDBPassword
      Runtime: java11
      Timeout: 30
      MemorySize: 512
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

  PostHelloWorldFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-PostHelloWorldFunc'
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Environment:
        Variables:
          spring_cloud_function_definition: postHelloWorld
          DB_HOST: !Ref ComeInDBHost
          DB_PORT: !Ref ComeInDBPort
          DB_INSTANCE: !Ref ComeInDBInstance
          DB_USERNAME: !Ref ComeInDBUsername
          DB_PASSWORD: !Ref ComeInDBPassword          
      Runtime: java11
      Timeout: 30
      MemorySize: 512
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post

# Start Function - LoadTourTicketByDateFunc  
  LoadTourTicketByDateFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-LoadTourTicketByDateFunc'
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Environment:
        Variables:
          spring_cloud_function_definition: loadTourTicketByDate
          DB_HOST: !Ref ComeInDBHost
          DB_PORT: !Ref ComeInDBPort
          DB_INSTANCE: !Ref ComeInDBInstance
          DB_USERNAME: !Ref ComeInDBUsername
          DB_PASSWORD: !Ref ComeInDBPassword          
      Runtime: java11
      Timeout: 30
      MemorySize: 512
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn

  LoadTourTicketByDatePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LoadTourTicketByDateFunc
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ComeInRestApi}/*/POST/tour-tickets

  LoadTourTicketByDateResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ComeInRestApi
      ParentId: !GetAtt 
        - ComeInRestApi
        - RootResourceId
      PathPart: tour-tickets

  LoadTourTicketByDateMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ComeInRestApi
      ResourceId: !Ref LoadTourTicketByDateResource
      HttpMethod: POST
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ComeInAuthorizer
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri:  !Join ['', ['arn:aws:apigateway:', !Ref AWS::Region, ':lambda:path/2015-03-31/functions/', !GetAtt LoadTourTicketByDateFunc.Arn, '/invocations']]
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestTemplates: 
          'application/json': !Ref ComeInRequestTemplate
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              'application/json' : !Ref ComeInResponseTemplate
      MethodResponses:
        - StatusCode: 200
        
# End Function - LoadTourTicketByDateFunc  
                              
  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'
